import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { BackgroundBeams } from '@/components/ui/background-beams/background-beams'
import { FloatingNav } from '@/components/ui/floating-nav/floating-nav'
import { routes } from '@/constants/routes'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-black`}>
        <div className='flex h-screen flex-col items-center justify-start bg-black scroll-smooth'>
          <BackgroundBeams />
          <FloatingNav navItems={routes} />
          {children}
        </div>
      </body>
    </html>
  )
}
